/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountReference } from './account-reference';
import { BuyerContractTermCondition } from './buyer-contract-term-condition';
import { ContractReference } from './contract-reference';
import { ContractUniqueKey } from './contract-unique-key';
import { Participant } from './participant';
import { TradingAgreement } from './trading-agreement';
import { TradingAgreementDescription } from './trading-agreement-description';

/**
 * @type BuyerContract
 * @export
 */
export type BuyerContract = TradingAgreement;



