/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesQuoteIdentifierType } from './com-ibm-commerce-foundation-common-datatypes-quote-identifier-type';
import { ComIbmCommerceOrderFacadeDatatypesChannelType } from './com-ibm-commerce-order-facade-datatypes-channel-type';

/**
 * 
 * @export
 * @interface CartAssignedCoupon
 */
export interface CartAssignedCoupon {
    /**
     * 
     * @type {string}
     * @memberof CartAssignedCoupon
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof CartAssignedCoupon
     */
    quoteID?: string;
    /**
     * 
     * @type {Array<CartAssignedCoupon>}
     * @memberof CartAssignedCoupon
     */
    couponCode?: Array<CartAssignedCoupon>;
    /**
     * 
     * @type {string}
     * @memberof CartAssignedCoupon
     */
    externalOrderID?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesQuoteIdentifierType}
     * @memberof CartAssignedCoupon
     */
    quoteIdentifier?: ComIbmCommerceFoundationCommonDatatypesQuoteIdentifierType;
    /**
     * 
     * @type {string}
     * @memberof CartAssignedCoupon
     */
    buyerPONumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CartAssignedCoupon
     */
    customerOrderNumber?: string;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesChannelType}
     * @memberof CartAssignedCoupon
     */
    channel?: ComIbmCommerceOrderFacadeDatatypesChannelType;
}


