/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartOrderShippingInfo } from './cart-order-shipping-info';
import { CartShippingInfoOrderItem } from './cart-shipping-info-order-item';
import { CartShippingInfoUserDataField } from './cart-shipping-info-user-data-field';

/**
 * 
 * @export
 * @interface CartShippingInfo
 */
export interface CartShippingInfo {
    /**
     * 
     * @type {string}
     * @memberof CartShippingInfo
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof CartShippingInfo
     */
    shipAsComplete?: string;
    /**
     * 
     * @type {Array<CartShippingInfoUserDataField>}
     * @memberof CartShippingInfo
     */
    userDataField?: Array<CartShippingInfoUserDataField>;
    /**
     * 
     * @type {Array<CartShippingInfoOrderItem>}
     * @memberof CartShippingInfo
     */
    orderItem?: Array<CartShippingInfoOrderItem>;
    /**
     * 
     * @type {CartOrderShippingInfo}
     * @memberof CartShippingInfo
     */
    orderShippingInfo?: CartOrderShippingInfo;
}


