/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartUsablePaymentInformationProtocolData } from './cart-usable-payment-information-protocol-data';
import { CartUsablePaymentInformationUsableBillingAddress } from './cart-usable-payment-information-usable-billing-address';
import { CartUsablePaymentInformationUserDataField } from './cart-usable-payment-information-user-data-field';

/**
 * 
 * @export
 * @interface CartUsablePaymentInformation
 */
export interface CartUsablePaymentInformation {
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInformation
     */
    paymentTermConditionId?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInformation
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInformation
     */
    language?: string;
    /**
     * 
     * @type {Array<CartUsablePaymentInformationProtocolData>}
     * @memberof CartUsablePaymentInformation
     */
    protocolData?: Array<CartUsablePaymentInformationProtocolData>;
    /**
     * 
     * @type {Array<CartUsablePaymentInformationUsableBillingAddress>}
     * @memberof CartUsablePaymentInformation
     */
    usableBillingAddress?: Array<CartUsablePaymentInformationUsableBillingAddress>;
    /**
     * 
     * @type {string}
     * @memberof CartUsablePaymentInformation
     */
    paymentMethodName?: string;
    /**
     * 
     * @type {Array<CartUsablePaymentInformationUserDataField>}
     * @memberof CartUsablePaymentInformation
     */
    userDataField?: Array<CartUsablePaymentInformationUserDataField>;
}


