/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogIBMAdminDetailsItemDescriptionOverrideAttributes } from './catalog-ibmadmin-details-item-description-override-attributes';
import { CatalogIBMAdminDetailsItemDescriptionOverrideDescriptionOverrideIdentifier } from './catalog-ibmadmin-details-item-description-override-description-override-identifier';

/**
 * 
 * @export
 * @interface CatalogIBMAdminDetailsItemDescriptionOverride
 */
export interface CatalogIBMAdminDetailsItemDescriptionOverride {
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescriptionOverride
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescriptionOverride
     */
    keyword?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescriptionOverride
     */
    fullImage?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescriptionOverride
     */
    longDescription?: string;
    /**
     * 
     * @type {CatalogIBMAdminDetailsItemDescriptionOverrideDescriptionOverrideIdentifier}
     * @memberof CatalogIBMAdminDetailsItemDescriptionOverride
     */
    descriptionOverrideIdentifier?: CatalogIBMAdminDetailsItemDescriptionOverrideDescriptionOverrideIdentifier;
    /**
     * 
     * @type {Array<CatalogIBMAdminDetailsItemDescriptionOverrideAttributes>}
     * @memberof CatalogIBMAdminDetailsItemDescriptionOverride
     */
    attributes?: Array<CatalogIBMAdminDetailsItemDescriptionOverrideAttributes>;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescriptionOverride
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemDescriptionOverride
     */
    thumbnail?: string;
}


