/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogEntryIBMAdminStandardOfferPriceItemDescription } from './catalog-entry-ibmadmin-standard-offer-price-item-description';
import { CatalogEntryIBMAdminStandardOfferPriceItemUserDataField } from './catalog-entry-ibmadmin-standard-offer-price-item-user-data-field';
import { ComIbmCommerceFoundationCommonDatatypesMonetaryAmountType } from './com-ibm-commerce-foundation-common-datatypes-monetary-amount-type';

/**
 * 
 * @export
 * @interface CatalogEntryIBMAdminStandardOfferPriceItem
 */
export interface CatalogEntryIBMAdminStandardOfferPriceItem {
    /**
     * 
     * @type {Array<CatalogEntryIBMAdminStandardOfferPriceItemDescription>}
     * @memberof CatalogEntryIBMAdminStandardOfferPriceItem
     */
    description?: Array<CatalogEntryIBMAdminStandardOfferPriceItemDescription>;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntryIBMAdminStandardOfferPriceItem
     */
    owningStoreDirectory?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesMonetaryAmountType}
     * @memberof CatalogEntryIBMAdminStandardOfferPriceItem
     */
    price?: ComIbmCommerceFoundationCommonDatatypesMonetaryAmountType;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntryIBMAdminStandardOfferPriceItem
     */
    uniqueID?: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntryIBMAdminStandardOfferPriceItem
     */
    partNumber: string;
    /**
     * 
     * @type {string}
     * @memberof CatalogEntryIBMAdminStandardOfferPriceItem
     */
    type?: string;
    /**
     * 
     * @type {Array<CatalogEntryIBMAdminStandardOfferPriceItemUserDataField>}
     * @memberof CatalogEntryIBMAdminStandardOfferPriceItem
     */
    userDataField?: Array<CatalogEntryIBMAdminStandardOfferPriceItemUserDataField>;
}


