/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset } from './catalog-ibmadmin-details-item-attachment-reference-attachment-asset';
import { CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentDescription } from './catalog-ibmadmin-details-item-attachment-reference-attachment-description';
import { CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentIdentifier } from './catalog-ibmadmin-details-item-attachment-reference-attachment-identifier';
import { CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentReferenceDescription } from './catalog-ibmadmin-details-item-attachment-reference-attachment-reference-description';
import { CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentReferenceIdentifier } from './catalog-ibmadmin-details-item-attachment-reference-attachment-reference-identifier';
import { CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentUsage } from './catalog-ibmadmin-details-item-attachment-reference-attachment-usage';
import { CatalogIBMAdminDetailsItemAttachmentReferenceUserData } from './catalog-ibmadmin-details-item-attachment-reference-user-data';

/**
 * 
 * @export
 * @interface CatalogIBMAdminDetailsItemAttachmentReference
 */
export interface CatalogIBMAdminDetailsItemAttachmentReference {
    /**
     * 
     * @type {CatalogIBMAdminDetailsItemAttachmentReferenceUserData}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReference
     */
    userData?: CatalogIBMAdminDetailsItemAttachmentReferenceUserData;
    /**
     * 
     * @type {CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentIdentifier}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReference
     */
    attachmentIdentifier?: CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentIdentifier;
    /**
     * 
     * @type {CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentReferenceIdentifier}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReference
     */
    attachmentReferenceIdentifier?: CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentReferenceIdentifier;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReference
     */
    displaySequence?: string;
    /**
     * 
     * @type {Array<CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentReferenceDescription>}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReference
     */
    attachmentReferenceDescription?: Array<CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentReferenceDescription>;
    /**
     * 
     * @type {Array<CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset>}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReference
     */
    attachmentAsset?: Array<CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentAsset>;
    /**
     * 
     * @type {Array<CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentDescription>}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReference
     */
    attachmentDescription?: Array<CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentDescription>;
    /**
     * 
     * @type {CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentUsage}
     * @memberof CatalogIBMAdminDetailsItemAttachmentReference
     */
    attachmentUsage?: CatalogIBMAdminDetailsItemAttachmentReferenceAttachmentUsage;
}


