/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogIBMAdminDetailsItemAttachmentReference } from './catalog-ibmadmin-details-item-attachment-reference';
import { CatalogIBMAdminDetailsItemAttributes } from './catalog-ibmadmin-details-item-attributes';
import { CatalogIBMAdminDetailsItemDescription } from './catalog-ibmadmin-details-item-description';

/**
 * 
 * @export
 * @interface CatalogIBMAdminDetailsItem
 */
export interface CatalogIBMAdminDetailsItem {
    /**
     * 
     * @type {Array<CatalogIBMAdminDetailsItemDescription>}
     * @memberof CatalogIBMAdminDetailsItem
     */
    description?: Array<CatalogIBMAdminDetailsItemDescription>;
    /**
     * 
     * @type {boolean}
     * @memberof CatalogIBMAdminDetailsItem
     */
    _default?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CatalogIBMAdminDetailsItem
     */
    primary?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItem
     */
    catalogId?: string;
    /**
     * 
     * @type {Array<CatalogIBMAdminDetailsItemAttachmentReference>}
     * @memberof CatalogIBMAdminDetailsItem
     */
    attachmentReference?: Array<CatalogIBMAdminDetailsItemAttachmentReference>;
    /**
     * 
     * @type {Array<CatalogIBMAdminDetailsItemAttributes>}
     * @memberof CatalogIBMAdminDetailsItem
     */
    attributes?: Array<CatalogIBMAdminDetailsItemAttributes>;
    /**
     * 
     * @type {string}
     * @memberof CatalogIBMAdminDetailsItem
     */
    catalogIdentifier: string;
}


