/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentAsset } from './category-ibmadmin-details-breadcrumb-item-attachment-reference-attachment-asset';
import { CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentDescription } from './category-ibmadmin-details-breadcrumb-item-attachment-reference-attachment-description';
import { CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentIdentifier } from './category-ibmadmin-details-breadcrumb-item-attachment-reference-attachment-identifier';
import { CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentReferenceDescription } from './category-ibmadmin-details-breadcrumb-item-attachment-reference-attachment-reference-description';
import { CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentReferenceIdentifier } from './category-ibmadmin-details-breadcrumb-item-attachment-reference-attachment-reference-identifier';
import { CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsage } from './category-ibmadmin-details-breadcrumb-item-attachment-reference-attachment-usage';
import { CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceUserData } from './category-ibmadmin-details-breadcrumb-item-attachment-reference-user-data';

/**
 * 
 * @export
 * @interface CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference
 */
export interface CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference {
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceUserData}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference
     */
    userData?: CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceUserData;
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentIdentifier}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference
     */
    attachmentIdentifier?: CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentIdentifier;
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentReferenceIdentifier}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference
     */
    attachmentReferenceIdentifier?: CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentReferenceIdentifier;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference
     */
    displaySequence?: string;
    /**
     * 
     * @type {Array<CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentReferenceDescription>}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference
     */
    attachmentReferenceDescription?: Array<CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentReferenceDescription>;
    /**
     * 
     * @type {Array<CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentAsset>}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference
     */
    attachmentAsset?: Array<CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentAsset>;
    /**
     * 
     * @type {Array<CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentDescription>}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference
     */
    attachmentDescription?: Array<CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentDescription>;
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsage}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReference
     */
    attachmentUsage?: CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsage;
}


