/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationshipAttributes } from './category-ibmadmin-details-breadcrumb-item-navigation-relationship-attributes';
import { CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationshipCatalogEntryReference } from './category-ibmadmin-details-breadcrumb-item-navigation-relationship-catalog-entry-reference';
import { CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationshipCatalogGroupReference } from './category-ibmadmin-details-breadcrumb-item-navigation-relationship-catalog-group-reference';

/**
 * 
 * @export
 * @interface CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationship
 */
export interface CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationship {
    /**
     * 
     * @type {Array<CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationshipAttributes>}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationship
     */
    attributes?: Array<CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationshipAttributes>;
    /**
     * 
     * @type {number}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationship
     */
    displaySequence?: number;
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationshipCatalogGroupReference}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationship
     */
    catalogGroupReference?: CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationshipCatalogGroupReference;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationship
     */
    type?: string;
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationshipCatalogEntryReference}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationship
     */
    catalogEntryReference?: CategoryIBMAdminDetailsBreadcrumbItemNavigationRelationshipCatalogEntryReference;
}


