/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeywordUserData } from './category-ibmadmin-details-breadcrumb-item-seourlurlkeyword-user-data';

/**
 * 
 * @export
 * @interface CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
 */
export interface CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword {
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeywordUserData}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    userData?: CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeywordUserData;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    keyword?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    generatedMobileKeyword?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    uRLPrefix?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    mobileURLPrefix?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    previewURL?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    mobileKeyword?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    generatedKeyword?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLURLKeyword
     */
    previewMobileURL?: string;
}


