/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescriptionUserData } from './category-ibmadmin-details-breadcrumb-item-attachment-reference-attachment-usage-attachment-usage-description-user-data';

/**
 * 
 * @export
 * @interface CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescription
 */
export interface CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescription {
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescriptionUserData}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescription
     */
    userData?: CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescriptionUserData;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescription
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescription
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescription
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemAttachmentReferenceAttachmentUsageAttachmentUsageDescription
     */
    longDescription?: string;
}


