/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfoUserData } from './category-ibmadmin-details-breadcrumb-item-seourlsite-map-info-user-data';

/**
 * 
 * @export
 * @interface CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfo
 */
export interface CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfo {
    /**
     * 
     * @type {number}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfo
     */
    priority?: number;
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfoUserData}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfo
     */
    userData?: CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfoUserData;
    /**
     * 
     * @type {number}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfo
     */
    mobilePriority?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfo
     */
    changeFrequency?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemSEOURLSiteMapInfo
     */
    mobileChangeFrequency?: string;
}


