/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifierAttributeDictionaryIdentifier } from './category-ibmadmin-details-breadcrumb-item-taxonomy-attribute-attribute-external-identifier-attribute-dictionary-identifier';
import { CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifierStoreIdentifier } from './category-ibmadmin-details-breadcrumb-item-taxonomy-attribute-attribute-external-identifier-store-identifier';

/**
 * 
 * @export
 * @interface CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifier
 */
export interface CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifier {
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifierAttributeDictionaryIdentifier}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifier
     */
    attributeDictionaryIdentifier: CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifierAttributeDictionaryIdentifier;
    /**
     * 
     * @type {CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifierStoreIdentifier}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifier
     */
    storeIdentifier?: CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifierStoreIdentifier;
    /**
     * 
     * @type {string}
     * @memberof CategoryIBMAdminDetailsBreadcrumbItemTaxonomyAttributeAttributeExternalIdentifier
     */
    identifier: string;
}


