/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSessionCookie } from './com-ibm-commerce-infrastructure-beans-integration-configuration-data-bean-session-cookie';
import { ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSessionLoginTimeout } from './com-ibm-commerce-infrastructure-beans-integration-configuration-data-bean-session-login-timeout';
import { ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSessionPersistentSession } from './com-ibm-commerce-infrastructure-beans-integration-configuration-data-bean-session-persistent-session';

/**
 * 
 * @export
 * @interface ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSession
 */
export interface ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSession {
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSession
     */
    referrerCookieAge?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSession
     */
    allowMultiLogon?: boolean;
    /**
     * 
     * @type {ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSessionCookie}
     * @memberof ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSession
     */
    cookie?: ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSessionCookie;
    /**
     * 
     * @type {ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSessionLoginTimeout}
     * @memberof ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSession
     */
    loginTimeout?: ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSessionLoginTimeout;
    /**
     * 
     * @type {ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSessionPersistentSession}
     * @memberof ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSession
     */
    persistentSession?: ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSessionPersistentSession;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceInfrastructureBeansIntegrationConfigurationDataBeanSession
     */
    keepSessionAliveEnabled?: boolean;
}


