/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressMobilePhone1UserData } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-purchaser-address-mobile-phone1-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressMobilePhone1
 */
export interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressMobilePhone1 {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressMobilePhone1
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressMobilePhone1
     */
    value: string;
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressMobilePhone1UserData}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressMobilePhone1
     */
    userData?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchaserAddressMobilePhone1UserData;
}


