/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The recipients of the e-mail.
 * @export
 * @interface ComIbmCommerceRestWishlistHandlerWishlistHandlerProcessBodyParameterDescriptionAnnouncementBodyDescriptionEmailRecipient
 */
export interface ComIbmCommerceRestWishlistHandlerWishlistHandlerProcessBodyParameterDescriptionAnnouncementBodyDescriptionEmailRecipient {
    /**
     * E-mail address of the recipient.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerProcessBodyParameterDescriptionAnnouncementBodyDescriptionEmailRecipient
     */
    recipientEmail: string;
    /**
     * The method in which the recipient is addressed in the e-mail, for example, they are directly addressed (TO), they are copied on the mail (CC), and so on.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerProcessBodyParameterDescriptionAnnouncementBodyDescriptionEmailRecipient
     */
    addressingMethod: string;
    /**
     * The name of the sender.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerProcessBodyParameterDescriptionAnnouncementBodyDescriptionEmailRecipient
     */
    recipientName: string;
}


