/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
 */
export interface ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    approvalStatusId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    approverGroupId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    submitTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    flowTypeId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    stateId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    submitterId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    flowId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    approveTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    approverId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceApprovalBeansApprovalStatusDataBeanIBMStoreSummary
     */
    entityId?: string;
}


