/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
 */
export interface ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    income?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    numberOfChildren?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    numberOfHouseholds?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    hobbies?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    incomeCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    timezone?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    companyName?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    orderBefore?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    age?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceUserBeansUserSearchDataBeanIBMUserListDetailsUserDataBeansDemographics
     */
    maritalStatus?: string;
}


