/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeCSRIdentifier } from './com-ibm-commerce-order-facade-datatypes-csrcomments-type-csridentifier';
import { ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCode } from './com-ibm-commerce-order-facade-datatypes-csrcomments-type-change-reason-code';
import { ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeUserData } from './com-ibm-commerce-order-facade-datatypes-csrcomments-type-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceOrderFacadeDatatypesCSRCommentsType
 */
export interface ComIbmCommerceOrderFacadeDatatypesCSRCommentsType {
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeCSRIdentifier}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsType
     */
    cSRIdentifier?: ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeCSRIdentifier;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsType
     */
    comment?: string;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeUserData}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsType
     */
    userData?: ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeUserData;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCode}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsType
     */
    changeReasonCode?: ComIbmCommerceOrderFacadeDatatypesCSRCommentsTypeChangeReasonCode;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsType
     */
    orderVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesCSRCommentsType
     */
    creationDate?: string;
}


