/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesSEOPropertiesTypeParentStoreIdentifier } from './com-ibm-commerce-foundation-common-datatypes-seoproperties-type-parent-store-identifier';
import { ComIbmCommerceFoundationCommonDatatypesSEOPropertiesTypeUserData } from './com-ibm-commerce-foundation-common-datatypes-seoproperties-type-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
 */
export interface ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType {
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    resolved?: boolean;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSEOPropertiesTypeUserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesSEOPropertiesTypeUserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    metaKeyword?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    fullImageAltDescription?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSEOPropertiesTypeParentStoreIdentifier}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    parentStoreIdentifier?: ComIbmCommerceFoundationCommonDatatypesSEOPropertiesTypeParentStoreIdentifier;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    pageGroup?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    objectIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    sEOPageDefID?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOPropertiesType
     */
    metaDescription?: string;
}


