/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddressUserData } from './com-ibm-commerce-foundation-common-datatypes-contact-info-type-address-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
 */
export interface ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
     */
    city?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
     */
    addressLine?: Array<string>;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddressUserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddressUserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
     */
    country?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
     */
    primary?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
     */
    stateOrProvinceName?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeAddress
     */
    internalOfficeAddress?: string;
}


