/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifier } from './com-ibm-commerce-order-facade-datatypes-promotion-code-type-associated-promotion-promotion-identifier-calculation-code-identifier-calculation-code-external-identifier-store-identifier';

/**
 * 
 * @export
 * @interface ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifier
 */
export interface ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifier {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifier
     */
    calculationUsageID?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifier
     */
    code?: string;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifier}
     * @memberof ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifier
     */
    storeIdentifier?: ComIbmCommerceOrderFacadeDatatypesPromotionCodeTypeAssociatedPromotionPromotionIdentifierCalculationCodeIdentifierCalculationCodeExternalIdentifierStoreIdentifier;
}


