/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeywordUserData } from './com-ibm-commerce-foundation-common-datatypes-seourltype-urlkeyword-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
 */
export interface ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword {
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeywordUserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeywordUserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    keyword?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    generatedMobileKeyword?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    uRLPrefix?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    mobileURLPrefix?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    previewURL?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    mobileKeyword?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    generatedKeyword?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeURLKeyword
     */
    previewMobileURL?: string;
}


