/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreviewPreviewProperties } from './com-ibm-commerce-rest-member-handler-user-context-handler-user-context-preview-preview-properties';

/**
 * User\'s preview information.
 * @export
 * @interface ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreview
 */
export interface ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreview {
    /**
     * The initial time difference when preview started.
     * @type {number}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreview
     */
    initialtimeDiff?: number;
    /**
     * 
     * @type {ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreviewPreviewProperties}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreview
     */
    previewProperties?: ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreviewPreviewProperties;
    /**
     * Is the preview session time static.
     * @type {boolean}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreview
     */
    _static?: boolean;
    /**
     * The preview timestamp.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerUserContextHandlerUserContextPreview
     */
    timestamp?: string;
}


