/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone2UserData } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-registrant-type-registrant-address-telephone2-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone2
 */
export interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone2 {
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone2UserData}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone2
     */
    userData?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone2UserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone2
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone2
     */
    value: string;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListRegistrantTypeRegistrantAddressTelephone2
     */
    publish?: boolean;
}


