/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesContactInfoTypeContactInfoIdentifierExternalIdentifierPersonIdentifierExternalIdentifier } from './com-ibm-commerce-foundation-common-datatypes-contact-info-type-contact-info-identifier-external-identifier-person-identifier-external-identifier';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesContactInfoTypeContactInfoIdentifierExternalIdentifierPersonIdentifier
 */
export interface ComIbmCommerceFoundationCommonDatatypesContactInfoTypeContactInfoIdentifierExternalIdentifierPersonIdentifier {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeContactInfoIdentifierExternalIdentifierPersonIdentifier
     */
    distinguishedName?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeContactInfoIdentifierExternalIdentifierPersonIdentifier
     */
    uniqueID?: string;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesContactInfoTypeContactInfoIdentifierExternalIdentifierPersonIdentifierExternalIdentifier}
     * @memberof ComIbmCommerceFoundationCommonDatatypesContactInfoTypeContactInfoIdentifierExternalIdentifierPersonIdentifier
     */
    externalIdentifier?: ComIbmCommerceFoundationCommonDatatypesContactInfoTypeContactInfoIdentifierExternalIdentifierPersonIdentifierExternalIdentifier;
}


