/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeCatalogEntryIdentifier } from './com-ibm-commerce-order-facade-datatypes-order-item-component-type-catalog-entry-identifier';
import { ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeOrderItemComponentIdentifier } from './com-ibm-commerce-order-facade-datatypes-order-item-component-type-order-item-component-identifier';
import { ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeQuantity } from './com-ibm-commerce-order-facade-datatypes-order-item-component-type-quantity';
import { ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeUnitPrice } from './com-ibm-commerce-order-facade-datatypes-order-item-component-type-unit-price';
import { ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeUserData } from './com-ibm-commerce-order-facade-datatypes-order-item-component-type-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceOrderFacadeDatatypesOrderItemComponentType
 */
export interface ComIbmCommerceOrderFacadeDatatypesOrderItemComponentType {
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeCatalogEntryIdentifier}
     * @memberof ComIbmCommerceOrderFacadeDatatypesOrderItemComponentType
     */
    catalogEntryIdentifier?: ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeCatalogEntryIdentifier;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeUserData}
     * @memberof ComIbmCommerceOrderFacadeDatatypesOrderItemComponentType
     */
    userData?: ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeUserData;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeOrderItemComponentIdentifier}
     * @memberof ComIbmCommerceOrderFacadeDatatypesOrderItemComponentType
     */
    orderItemComponentIdentifier?: ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeOrderItemComponentIdentifier;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceOrderFacadeDatatypesOrderItemComponentType
     */
    configurationID?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceOrderFacadeDatatypesOrderItemComponentType
     */
    required?: boolean;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeUnitPrice}
     * @memberof ComIbmCommerceOrderFacadeDatatypesOrderItemComponentType
     */
    unitPrice?: ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeUnitPrice;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeQuantity}
     * @memberof ComIbmCommerceOrderFacadeDatatypesOrderItemComponentType
     */
    quantity?: ComIbmCommerceOrderFacadeDatatypesOrderItemComponentTypeQuantity;
}


