/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants } from './com-ibm-commerce-contract-beans-extended-term-condition-data-bean-ibmstore-details-participants';

/**
 * 
 * @export
 * @interface ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
 */
export interface ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    termConditionId?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    XMLString?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    timeCreated?: string;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    changeableFlag?: number;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    tcSequence?: number;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    mandatoryFlag?: number;
    /**
     * 
     * @type {Array<ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants>}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    participants?: Array<ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants>;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    tcSubType?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    timeUpdated?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetails
     */
    tradingId?: string;
}


