/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListUpdateResponseItem } from './com-ibm-commerce-rest-wishlist-handler-wishlist-handler-wish-list-update-response-item';

/**
 * 
 * @export
 * @interface ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListUpdateResponse
 */
export interface ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListUpdateResponse {
    /**
     * Wish list item to add or update.
     * @type {Array<ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListUpdateResponseItem>}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListUpdateResponse
     */
    item?: Array<ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListUpdateResponseItem>;
    /**
     * Wish list unique identifier.
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListUpdateResponse
     */
    uniqueID: string;
    /**
     * Wish list descriptionName
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListUpdateResponse
     */
    descriptionName?: string;
    /**
     * Wish list resource name
     * @type {string}
     * @memberof ComIbmCommerceRestWishlistHandlerWishlistHandlerWishListUpdateResponse
     */
    resourceName: string;
}


