/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information required to add CSR comment.
 * @export
 * @interface ComIbmCommerceRestOrderHandlerOrderHandlerCSRCommentForm
 */
export interface ComIbmCommerceRestOrderHandlerOrderHandlerCSRCommentForm {
    /**
     * The comment field.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerOrderHandlerCSRCommentForm
     */
    commentField: string;
    /**
     * The email address.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerOrderHandlerCSRCommentForm
     */
    emailAddress?: string;
    /**
     * The flag to indicate to send email or not.
     * @type {boolean}
     * @memberof ComIbmCommerceRestOrderHandlerOrderHandlerCSRCommentForm
     */
    sendEmail?: boolean;
}


