/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsItemBought } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-purchased-item-details-item-bought';
import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsOrderItemIdentifier } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-purchased-item-details-order-item-identifier';
import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsQuantity } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-purchased-item-details-quantity';
import { ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsUserData } from './com-ibm-commerce-giftcenter-facade-datatypes-gift-list-purchase-record-type-purchased-item-details-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails
 */
export interface ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails {
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsUserData}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails
     */
    userData?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsUserData;
    /**
     * 
     * @type {boolean}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails
     */
    itemShippedToRegistrant?: boolean;
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsItemBought}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails
     */
    itemBought: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsItemBought;
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsOrderItemIdentifier}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails
     */
    orderItemIdentifier?: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsOrderItemIdentifier;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails
     */
    transactionID?: string;
    /**
     * 
     * @type {ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsQuantity}
     * @memberof ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetails
     */
    quantity: ComIbmCommerceGiftcenterFacadeDatatypesGiftListPurchaseRecordTypePurchasedItemDetailsQuantity;
}


