/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about a guest user identity.
 * @export
 * @interface ComIbmCommerceRestMemberHandlerGuestIdentityHandlerUserIdentity
 */
export interface ComIbmCommerceRestMemberHandlerGuestIdentityHandlerUserIdentity {
    /**
     * The user unique identifier.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerGuestIdentityHandlerUserIdentity
     */
    userId: string;
    /**
     * The token used for authentication.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerGuestIdentityHandlerUserIdentity
     */
    WCToken: string;
    /**
     * The trusted token used for authentication. This token should only be used on encrypted channels.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerGuestIdentityHandlerUserIdentity
     */
    WCTrustedToken: string;
    /**
     * The personalization identifier for the current session.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerGuestIdentityHandlerUserIdentity
     */
    personalizationID: string;
}


