/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants
 */
export interface ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants {
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants
     */
    termConditionId?: number;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants
     */
    participantId?: number;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants
     */
    timeCreated?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants
     */
    information?: string;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants
     */
    roleId?: number;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants
     */
    memberId?: number;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants
     */
    timeUpdated?: string;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceContractBeansExtendedTermConditionDataBeanIBMStoreDetailsParticipants
     */
    tradingId?: number;
}


