/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ComIbmCommerceRestOrderHandlerCartHandlerSetPendingOrderRequest
 */
export interface ComIbmCommerceRestOrderHandlerCartHandlerSetPendingOrderRequest {
    /**
     * Specifies an order using the order reference number or one of the Order abbreviations. If the parameter is omitted, all the pending orders is set to current. If a specified pending order no longer exists, it is not set to current.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerSetPendingOrderRequest
     */
    orderId?: string;
    /**
     * The reference number of a destination order.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerSetPendingOrderRequest
     */
    outOrderName?: string;
}


