/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Store information.
 * @export
 * @interface ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
 */
export interface ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation {
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    resourceName?: string;
    /**
     * Store geonode api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    geonodeUrl: string;
    /**
     * Store person api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    personUrl: string;
    /**
     * Store name.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    storeName: string;
    /**
     * Store locator api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    storeLocatorUrl: string;
    /**
     * Store order api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    orderUrl: string;
    /**
     * Store e-spots api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    espotUrl: string;
    /**
     * Store top categories api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    topcategoriesUrl: string;
    /**
     * Store inventory api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    inventoryavailabilityUrl: string;
    /**
     * Store product api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    productUrl: string;
    /**
     * Store wish list api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    wishlistUrl: string;
    /**
     * Store identifier.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    storeId: string;
    /**
     * Store directory name.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    directory: string;
    /**
     * Store guest identity api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    guestidentityUrl: string;
    /**
     * Store login api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    loginidentityUrl: string;
    /**
     * Store shopping cart api url.
     * @type {string}
     * @memberof ComIbmCommerceRestStoreHandlerStoreHandlerStoreInformation
     */
    shoppingcartUrl: string;
}


