/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Description of the addOrderItem input body.
 * @export
 * @interface ComIbmCommerceRestOrderHandlerCartHandlerAddPreConfigurationToCartRequest
 */
export interface ComIbmCommerceRestOrderHandlerCartHandlerAddPreConfigurationToCartRequest {
    /**
     * The identifier of the Order.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerAddPreConfigurationToCartRequest
     */
    orderId?: string;
    /**
     * The quantity of the item to be added to the order
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerAddPreConfigurationToCartRequest
     */
    quantity?: string;
    /**
     * Specifies whether OrderCalculateCmd will be called to calculate the charges for the order. 0 = do not call OrderCalculateCmd, 1 = call OrderCalculateCmd.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerAddPreConfigurationToCartRequest
     */
    calculateOrder?: string;
    /**
     * The identifier for the type of calculation to be performed on the order.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerAddPreConfigurationToCartRequest
     */
    calculationUsage?: string;
    /**
     * he part number of catalog entry.
     * @type {string}
     * @memberof ComIbmCommerceRestOrderHandlerCartHandlerAddPreConfigurationToCartRequest
     */
    partNumber?: string;
}


