/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfoUserData } from './com-ibm-commerce-foundation-common-datatypes-seourltype-site-map-info-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfo
 */
export interface ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfo {
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfo
     */
    priority?: number;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfoUserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfo
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfoUserData;
    /**
     * 
     * @type {number}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfo
     */
    mobilePriority?: number;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfo
     */
    changeFrequency?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSEOURLTypeSiteMapInfo
     */
    mobileChangeFrequency?: string;
}


