/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Information about an organization entity identity.
 * @export
 * @interface ComIbmCommerceRestMemberHandlerOrganizationHandlerUpdateApprovalGroupsResponse
 */
export interface ComIbmCommerceRestMemberHandlerOrganizationHandlerUpdateApprovalGroupsResponse {
    /**
     * The organization entity identifier.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerOrganizationHandlerUpdateApprovalGroupsResponse
     */
    orgEntityId: string;
    /**
     * The ApprovalGroup identifier for a specific organization.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerOrganizationHandlerUpdateApprovalGroupsResponse
     */
    segmentId: string;
    /**
     * The URL to call when the command completes successfully.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerOrganizationHandlerUpdateApprovalGroupsResponse
     */
    URL: string;
    /**
     * The current store identifier.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerOrganizationHandlerUpdateApprovalGroupsResponse
     */
    storeId?: string;
    /**
     * The catalog identifier.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerOrganizationHandlerUpdateApprovalGroupsResponse
     */
    catalogId?: string;
    /**
     * The request type for example, ajax.
     * @type {string}
     * @memberof ComIbmCommerceRestMemberHandlerOrganizationHandlerUpdateApprovalGroupsResponse
     */
    requesttype?: string;
}


