/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescriptionUserData } from './com-ibm-commerce-foundation-common-datatypes-attachment-reference-type-attachment-description-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescription
 */
export interface ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescription {
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescriptionUserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescription
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescriptionUserData;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescription
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescription
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescription
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof ComIbmCommerceFoundationCommonDatatypesAttachmentReferenceTypeAttachmentDescription
     */
    longDescription?: string;
}


