/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleEndInfo } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-payment-schedule-end-info';
import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleFrequencyInfo } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-payment-schedule-frequency-info';
import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleStartInfo } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-payment-schedule-start-info';
import { ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleUserData } from './com-ibm-commerce-foundation-common-datatypes-subscription-info-type-payment-schedule-user-data';

/**
 * 
 * @export
 * @interface ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentSchedule
 */
export interface ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentSchedule {
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleEndInfo}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentSchedule
     */
    endInfo?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleEndInfo;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleStartInfo}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentSchedule
     */
    startInfo?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleStartInfo;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleUserData}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentSchedule
     */
    userData?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleUserData;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleFrequencyInfo}
     * @memberof ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentSchedule
     */
    frequencyInfo?: ComIbmCommerceFoundationCommonDatatypesSubscriptionInfoTypePaymentScheduleFrequencyInfo;
}


