/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainer } from './com-ibm-commerce-rest-marketing-handler-espot-data-handler-espot-container-marketing-spot-data-container';

/**
 * Structure containing an e-marketing spot.
 * @export
 * @interface ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainer
 */
export interface ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainer {
    /**
     * Data to display in the e-marketing spot.
     * @type {Array<ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainer>}
     * @memberof ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainer
     */
    MarketingSpotData: Array<ComIbmCommerceRestMarketingHandlerESpotDataHandlerESpotContainerMarketingSpotDataContainer>;
}


