/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceFoundationCommonDatatypesDescriptionType } from './com-ibm-commerce-foundation-common-datatypes-description-type';
import { ConfigurationConfigurationAttributeType } from './configuration-configuration-attribute-type';
import { ConfigurationConfigurationItemUserDataField } from './configuration-configuration-item-user-data-field';

/**
 * 
 * @export
 * @interface ConfigurationConfigurationItem
 */
export interface ConfigurationConfigurationItem {
    /**
     * 
     * @type {string}
     * @memberof ConfigurationConfigurationItem
     */
    configurationId: string;
    /**
     * 
     * @type {Array<ConfigurationConfigurationAttributeType>}
     * @memberof ConfigurationConfigurationItem
     */
    configurationAttribute?: Array<ConfigurationConfigurationAttributeType>;
    /**
     * 
     * @type {ComIbmCommerceFoundationCommonDatatypesDescriptionType}
     * @memberof ConfigurationConfigurationItem
     */
    description?: ComIbmCommerceFoundationCommonDatatypesDescriptionType;
    /**
     * 
     * @type {Array<ConfigurationConfigurationItemUserDataField>}
     * @memberof ConfigurationConfigurationItem
     */
    userDataField?: Array<ConfigurationConfigurationItemUserDataField>;
}


