/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CouponCouponItem } from './coupon-coupon-item';

/**
 * 
 * @export
 * @interface CouponCoupon
 */
export interface CouponCoupon {
    /**
     * 
     * @type {Array<CouponCouponItem>}
     * @memberof CouponCoupon
     */
    Coupon?: Array<CouponCouponItem>;
    /**
     * 
     * @type {boolean}
     * @memberof CouponCoupon
     */
    recordSetComplete?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CouponCoupon
     */
    recordSetStartNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof CouponCoupon
     */
    recordSetCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CouponCoupon
     */
    recordSetTotal?: number;
}


