/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DisplayPriceIBMStoreDisplayPriceItemUnitPrice } from './display-price-ibmstore-display-price-item-unit-price';
import { DisplayPriceIBMStoreDisplayPriceItemUserDataField } from './display-price-ibmstore-display-price-item-user-data-field';

/**
 * 
 * @export
 * @interface DisplayPriceIBMStoreDisplayPriceItem
 */
export interface DisplayPriceIBMStoreDisplayPriceItem {
    /**
     * 
     * @type {string}
     * @memberof DisplayPriceIBMStoreDisplayPriceItem
     */
    partNumber: string;
    /**
     * 
     * @type {string}
     * @memberof DisplayPriceIBMStoreDisplayPriceItem
     */
    priceRuleId?: string;
    /**
     * 
     * @type {string}
     * @memberof DisplayPriceIBMStoreDisplayPriceItem
     */
    priceRuleName?: string;
    /**
     * 
     * @type {string}
     * @memberof DisplayPriceIBMStoreDisplayPriceItem
     */
    catalogEntryId?: string;
    /**
     * 
     * @type {Array<DisplayPriceIBMStoreDisplayPriceItemUnitPrice>}
     * @memberof DisplayPriceIBMStoreDisplayPriceItem
     */
    unitPrice?: Array<DisplayPriceIBMStoreDisplayPriceItemUnitPrice>;
    /**
     * 
     * @type {Array<DisplayPriceIBMStoreDisplayPriceItemUserDataField>}
     * @memberof DisplayPriceIBMStoreDisplayPriceItem
     */
    userDataField?: Array<DisplayPriceIBMStoreDisplayPriceItemUserDataField>;
}


