/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EspotCatalogGroupNavigationRelationshipCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifier } from './espot-catalog-group-navigation-relationship-catalog-group-reference-catalog-group-identifier-external-identifier-store-identifier';

/**
 * 
 * @export
 * @interface EspotCatalogGroupNavigationRelationshipCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifier
 */
export interface EspotCatalogGroupNavigationRelationshipCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifier {
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupNavigationRelationshipCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifier
     */
    ownerID?: string;
    /**
     * 
     * @type {EspotCatalogGroupNavigationRelationshipCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifier}
     * @memberof EspotCatalogGroupNavigationRelationshipCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifier
     */
    storeIdentifier?: EspotCatalogGroupNavigationRelationshipCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifierStoreIdentifier;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupNavigationRelationshipCatalogGroupReferenceCatalogGroupIdentifierExternalIdentifier
     */
    groupIdentifier: string;
}


