/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifierAttributeDictionaryIdentifier } from './espot-catalog-group-taxonomy-attribute-attribute-external-identifier-attribute-dictionary-identifier';
import { EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifierStoreIdentifier } from './espot-catalog-group-taxonomy-attribute-attribute-external-identifier-store-identifier';

/**
 * 
 * @export
 * @interface EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifier
 */
export interface EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifier {
    /**
     * 
     * @type {EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifierAttributeDictionaryIdentifier}
     * @memberof EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifier
     */
    attributeDictionaryIdentifier: EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifierAttributeDictionaryIdentifier;
    /**
     * 
     * @type {EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifierStoreIdentifier}
     * @memberof EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifier
     */
    storeIdentifier?: EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifierStoreIdentifier;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupTaxonomyAttributeAttributeExternalIdentifier
     */
    identifier: string;
}


