/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JavaUtilMapEntry } from './java-util-map-entry';

/**
 * 
 * @export
 * @interface EspotCatalogGroupDescription
 */
export interface EspotCatalogGroupDescription {
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupDescription
     */
    categoryName?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupDescription
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupDescription
     */
    fullImage?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupDescription
     */
    longDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupDescription
     */
    keyword?: string;
    /**
     * 
     * @type {Array<JavaUtilMapEntry>}
     * @memberof EspotCatalogGroupDescription
     */
    attributes?: Array<JavaUtilMapEntry>;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupDescription
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupDescription
     */
    thumbnail?: string;
}


