/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EspotCatalogGroupAssociationCatalogGroupReferenceCatalogGroupIdentifier } from './espot-catalog-group-association-catalog-group-reference-catalog-group-identifier';
import { EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifier } from './espot-catalog-group-association-catalog-group-reference-catalog-identifier';

/**
 * 
 * @export
 * @interface EspotCatalogGroupAssociationCatalogGroupReference
 */
export interface EspotCatalogGroupAssociationCatalogGroupReference {
    /**
     * 
     * @type {EspotCatalogGroupAssociationCatalogGroupReferenceCatalogGroupIdentifier}
     * @memberof EspotCatalogGroupAssociationCatalogGroupReference
     */
    catalogGroupIdentifier?: EspotCatalogGroupAssociationCatalogGroupReferenceCatalogGroupIdentifier;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupAssociationCatalogGroupReference
     */
    displayName: string;
    /**
     * 
     * @type {EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifier}
     * @memberof EspotCatalogGroupAssociationCatalogGroupReference
     */
    catalogIdentifier?: EspotCatalogGroupAssociationCatalogGroupReferenceCatalogIdentifier;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupAssociationCatalogGroupReference
     */
    navigationPath?: string;
}


