/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EspotCatalogGroupExternalContentReferenceExternalContentAsset } from './espot-catalog-group-external-content-reference-external-content-asset';
import { EspotCatalogGroupExternalContentReferenceUserData } from './espot-catalog-group-external-content-reference-user-data';

/**
 * 
 * @export
 * @interface EspotCatalogGroupExternalContentReference
 */
export interface EspotCatalogGroupExternalContentReference {
    /**
     * 
     * @type {EspotCatalogGroupExternalContentReferenceUserData}
     * @memberof EspotCatalogGroupExternalContentReference
     */
    userData?: EspotCatalogGroupExternalContentReferenceUserData;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupExternalContentReference
     */
    externalContentDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupExternalContentReference
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupExternalContentReference
     */
    lastUpdateTime?: string;
    /**
     * 
     * @type {Array<EspotCatalogGroupExternalContentReferenceExternalContentAsset>}
     * @memberof EspotCatalogGroupExternalContentReference
     */
    externalContentAsset?: Array<EspotCatalogGroupExternalContentReferenceExternalContentAsset>;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupExternalContentReference
     */
    uniqueID?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupExternalContentReference
     */
    externalContentIdentifier: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupExternalContentReference
     */
    externalContentType?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupExternalContentReference
     */
    name: string;
}


