/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EspotCatalogGroupNavigationRelationshipAttributes } from './espot-catalog-group-navigation-relationship-attributes';
import { EspotCatalogGroupNavigationRelationshipCatalogEntryReference } from './espot-catalog-group-navigation-relationship-catalog-entry-reference';
import { EspotCatalogGroupNavigationRelationshipCatalogGroupReference } from './espot-catalog-group-navigation-relationship-catalog-group-reference';

/**
 * 
 * @export
 * @interface EspotCatalogGroupNavigationRelationship
 */
export interface EspotCatalogGroupNavigationRelationship {
    /**
     * 
     * @type {Array<EspotCatalogGroupNavigationRelationshipAttributes>}
     * @memberof EspotCatalogGroupNavigationRelationship
     */
    attributes?: Array<EspotCatalogGroupNavigationRelationshipAttributes>;
    /**
     * 
     * @type {number}
     * @memberof EspotCatalogGroupNavigationRelationship
     */
    displaySequence?: number;
    /**
     * 
     * @type {EspotCatalogGroupNavigationRelationshipCatalogGroupReference}
     * @memberof EspotCatalogGroupNavigationRelationship
     */
    catalogGroupReference?: EspotCatalogGroupNavigationRelationshipCatalogGroupReference;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupNavigationRelationship
     */
    type?: string;
    /**
     * 
     * @type {EspotCatalogGroupNavigationRelationshipCatalogEntryReference}
     * @memberof EspotCatalogGroupNavigationRelationship
     */
    catalogEntryReference?: EspotCatalogGroupNavigationRelationshipCatalogEntryReference;
}


