/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EspotCatalogGroupSEOURLParentStoreIdentifier } from './espot-catalog-group-seourlparent-store-identifier';
import { EspotCatalogGroupSEOURLSiteMapInfo } from './espot-catalog-group-seourlsite-map-info';
import { EspotCatalogGroupSEOURLURLKeyword } from './espot-catalog-group-seourlurlkeyword';
import { EspotCatalogGroupSEOURLUserData } from './espot-catalog-group-seourluser-data';

/**
 * 
 * @export
 * @interface EspotCatalogGroupSEOURL
 */
export interface EspotCatalogGroupSEOURL {
    /**
     * 
     * @type {EspotCatalogGroupSEOURLUserData}
     * @memberof EspotCatalogGroupSEOURL
     */
    userData?: EspotCatalogGroupSEOURLUserData;
    /**
     * 
     * @type {EspotCatalogGroupSEOURLParentStoreIdentifier}
     * @memberof EspotCatalogGroupSEOURL
     */
    parentStoreIdentifier?: EspotCatalogGroupSEOURLParentStoreIdentifier;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOURL
     */
    tokenValue?: string;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOURL
     */
    uRLKeywordID?: string;
    /**
     * 
     * @type {Array<EspotCatalogGroupSEOURLURLKeyword>}
     * @memberof EspotCatalogGroupSEOURL
     */
    uRLKeyword?: Array<EspotCatalogGroupSEOURLURLKeyword>;
    /**
     * 
     * @type {string}
     * @memberof EspotCatalogGroupSEOURL
     */
    usage?: string;
    /**
     * 
     * @type {EspotCatalogGroupSEOURLSiteMapInfo}
     * @memberof EspotCatalogGroupSEOURL
     */
    siteMapInfo?: EspotCatalogGroupSEOURLSiteMapInfo;
}


