/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InventoryavailabilityInventoryavailabilityItemUserDataField } from './inventoryavailability-inventoryavailability-item-user-data-field';

/**
 * 
 * @export
 * @interface InventoryavailabilityInventoryavailabilityItem
 */
export interface InventoryavailabilityInventoryavailabilityItem {
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    physicalStoreName?: string;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    onlineStoreName?: string;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    availabilityDateTime?: string;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    onlineStoreId?: string;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    unitOfMeasure?: string;
    /**
     * 
     * @type {number}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    availableQuantity?: number;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    inventoryStatus?: string;
    /**
     * 
     * @type {Array<InventoryavailabilityInventoryavailabilityItemUserDataField>}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    userDataField?: Array<InventoryavailabilityInventoryavailabilityItemUserDataField>;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    physicalStoreId?: string;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    x_customField1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    x_customField2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    x_customField3?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InventoryavailabilityInventoryavailabilityItem
     */
    productId?: string;
}


