/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LayoutLayoutItemPageLocationUserDataField } from './layout-layout-item-page-location-user-data-field';

/**
 * 
 * @export
 * @interface LayoutLayoutItemPageLocation
 */
export interface LayoutLayoutItemPageLocation {
    /**
     * 
     * @type {boolean}
     * @memberof LayoutLayoutItemPageLocation
     */
    propagateToSubLevels?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemPageLocation
     */
    pageId?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemPageLocation
     */
    startDate?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemPageLocation
     */
    storeId?: string;
    /**
     * 
     * @type {number}
     * @memberof LayoutLayoutItemPageLocation
     */
    groupNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemPageLocation
     */
    pageGroup?: string;
    /**
     * 
     * @type {number}
     * @memberof LayoutLayoutItemPageLocation
     */
    priority?: number;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemPageLocation
     */
    activityId?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemPageLocation
     */
    applyToSubPage?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemPageLocation
     */
    searchTerm?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemPageLocation
     */
    endDate?: string;
    /**
     * 
     * @type {Array<LayoutLayoutItemPageLocationUserDataField>}
     * @memberof LayoutLayoutItemPageLocation
     */
    userDataField?: Array<LayoutLayoutItemPageLocationUserDataField>;
}


