/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LayoutLayoutItemLayoutPropertyUserDataField } from './layout-layout-item-layout-property-user-data-field';

/**
 * 
 * @export
 * @interface LayoutLayoutItemLayoutProperty
 */
export interface LayoutLayoutItemLayoutProperty {
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemLayoutProperty
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemLayoutProperty
     */
    layoutPropertyId?: string;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemLayoutProperty
     */
    value?: string;
    /**
     * 
     * @type {number}
     * @memberof LayoutLayoutItemLayoutProperty
     */
    sequenceOrder?: number;
    /**
     * 
     * @type {Array<LayoutLayoutItemLayoutPropertyUserDataField>}
     * @memberof LayoutLayoutItemLayoutProperty
     */
    userDataField?: Array<LayoutLayoutItemLayoutPropertyUserDataField>;
    /**
     * 
     * @type {string}
     * @memberof LayoutLayoutItemLayoutProperty
     */
    properties?: string;
}


