/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderOrderDetailRewardOptionRewardSpecificationGiftSetSpecification } from './order-order-detail-reward-option-reward-specification-gift-set-specification';
import { OrderOrderDetailRewardOptionRewardSpecificationUserData } from './order-order-detail-reward-option-reward-specification-user-data';

/**
 * 
 * @export
 * @interface OrderOrderDetailRewardOptionRewardSpecification
 */
export interface OrderOrderDetailRewardOptionRewardSpecification {
    /**
     * 
     * @type {OrderOrderDetailRewardOptionRewardSpecificationGiftSetSpecification}
     * @memberof OrderOrderDetailRewardOptionRewardSpecification
     */
    giftSetSpecification?: OrderOrderDetailRewardOptionRewardSpecificationGiftSetSpecification;
    /**
     * 
     * @type {OrderOrderDetailRewardOptionRewardSpecificationUserData}
     * @memberof OrderOrderDetailRewardOptionRewardSpecification
     */
    userData?: OrderOrderDetailRewardOptionRewardSpecificationUserData;
}


