/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceOrderFacadeDatatypesChannelType } from './com-ibm-commerce-order-facade-datatypes-channel-type';
import { OrderOrderDetailAdjustment } from './order-order-detail-adjustment';

/**
 * 
 * @export
 * @interface OrderOrderDetailsOrder
 */
export interface OrderOrderDetailsOrder {
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    orderTypeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalShippingCharge?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    resourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    orgUniqueID?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    orgDistinguishedName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    lastUpdateDate?: string;
    /**
     * 
     * @type {ComIbmCommerceOrderFacadeDatatypesChannelType}
     * @memberof OrderOrderDetailsOrder
     */
    channel?: ComIbmCommerceOrderFacadeDatatypesChannelType;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    orderStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    x_isPurchaseOrderNumberRequired?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalShippingChargeCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    buyerId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    grandTotalCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    buyerDistinguishedName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    x_isPersonalAddressesAllowedForShipping?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    storeNameIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalProductPriceCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalProductPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    locked?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    placedDate?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalAdjustmentCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalSalesTaxCurrency?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalSalesTax?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    grandTotal?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    storeUniqueID?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    shipAsComplete?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    x_trackingIds?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalShippingTax?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    prepareIndicator?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalShippingTaxCurrency?: string;
    /**
     * 
     * @type {Array<OrderOrderDetailAdjustment>}
     * @memberof OrderOrderDetailsOrder
     */
    adjustment?: Array<OrderOrderDetailAdjustment>;
    /**
     * 
     * @type {string}
     * @memberof OrderOrderDetailsOrder
     */
    totalAdjustment?: string;
}


