/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PageDesignSlot } from './page-design-slot';
import { PageDesignWidgetProperty } from './page-design-widget-property';
import { PageDesignWidgetUserDataField } from './page-design-widget-user-data-field';

/**
 * 
 * @export
 * @interface PageDesignWidget
 */
export interface PageDesignWidget {
    /**
     * 
     * @type {PageDesignSlot}
     * @memberof PageDesignWidget
     */
    slot?: PageDesignSlot;
    /**
     * 
     * @type {string}
     * @memberof PageDesignWidget
     */
    widgetDefinitionIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof PageDesignWidget
     */
    widgetDefinitionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PageDesignWidget
     */
    widgetId?: string;
    /**
     * 
     * @type {Array<PageDesignWidget>}
     * @memberof PageDesignWidget
     */
    childWidget?: Array<PageDesignWidget>;
    /**
     * 
     * @type {Array<PageDesignWidgetProperty>}
     * @memberof PageDesignWidget
     */
    widgetProperty?: Array<PageDesignWidgetProperty>;
    /**
     * 
     * @type {string}
     * @memberof PageDesignWidget
     */
    widgetDefinitionStoreId?: string;
    /**
     * 
     * @type {number}
     * @memberof PageDesignWidget
     */
    widgetSequence?: number;
    /**
     * 
     * @type {Array<PageDesignWidgetUserDataField>}
     * @memberof PageDesignWidget
     */
    userDataField?: Array<PageDesignWidgetUserDataField>;
    /**
     * 
     * @type {string}
     * @memberof PageDesignWidget
     */
    name?: string;
}


