/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommercePromotionFacadeDatatypesPromotionScheduleType } from './com-ibm-commerce-promotion-facade-datatypes-promotion-schedule-type';
import { PromotionPromotionItemDescription } from './promotion-promotion-item-description';

/**
 * 
 * @export
 * @interface PromotionPromotionItem
 */
export interface PromotionPromotionItem {
    /**
     * 
     * @type {string}
     * @memberof PromotionPromotionItem
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof PromotionPromotionItem
     */
    storeId?: string;
    /**
     * 
     * @type {Array<PromotionPromotionItemDescription>}
     * @memberof PromotionPromotionItem
     */
    Description?: Array<PromotionPromotionItemDescription>;
    /**
     * 
     * @type {ComIbmCommercePromotionFacadeDatatypesPromotionScheduleType}
     * @memberof PromotionPromotionItem
     */
    schedule?: ComIbmCommercePromotionFacadeDatatypesPromotionScheduleType;
    /**
     * 
     * @type {string}
     * @memberof PromotionPromotionItem
     */
    promotionName: string;
    /**
     * 
     * @type {string}
     * @memberof PromotionPromotionItem
     */
    administrativeName?: string;
    /**
     * 
     * @type {string}
     * @memberof PromotionPromotionItem
     */
    promotionType?: string;
    /**
     * 
     * @type {string}
     * @memberof PromotionPromotionItem
     */
    promotionId?: string;
}


