/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComIbmCommerceInfrastructureFacadeDatatypesDefaultCatalogType } from './com-ibm-commerce-infrastructure-facade-datatypes-default-catalog-type';
import { StoreOnlineStoreContactInfoType } from './store-online-store-contact-info-type';
import { StoreOnlineStoreDescriptionType } from './store-online-store-description-type';
import { StoreOnlineStoreRelatedStoresType } from './store-online-store-related-stores-type';
import { StoreOnlineStoreSupportedCurrenciesType } from './store-online-store-supported-currencies-type';
import { StoreOnlineStoreSupportedLanguagesType } from './store-online-store-supported-languages-type';

/**
 * 
 * @export
 * @interface StoreStoreItem
 */
export interface StoreStoreItem {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof StoreStoreItem
     */
    userData?: { [key: string]: string; };
    /**
     * 
     * @type {Array<StoreOnlineStoreContactInfoType>}
     * @memberof StoreStoreItem
     */
    contactInfo?: Array<StoreOnlineStoreContactInfoType>;
    /**
     * 
     * @type {Array<StoreOnlineStoreDescriptionType>}
     * @memberof StoreStoreItem
     */
    description?: Array<StoreOnlineStoreDescriptionType>;
    /**
     * 
     * @type {Array<StoreOnlineStoreRelatedStoresType>}
     * @memberof StoreStoreItem
     */
    relatedStores?: Array<StoreOnlineStoreRelatedStoresType>;
    /**
     * 
     * @type {string}
     * @memberof StoreStoreItem
     */
    storeId?: string;
    /**
     * 
     * @type {Array<StoreOnlineStoreContactInfoType>}
     * @memberof StoreStoreItem
     */
    locationInfo?: Array<StoreOnlineStoreContactInfoType>;
    /**
     * 
     * @type {Array<ComIbmCommerceInfrastructureFacadeDatatypesDefaultCatalogType>}
     * @memberof StoreStoreItem
     */
    defaultCatalog?: Array<ComIbmCommerceInfrastructureFacadeDatatypesDefaultCatalogType>;
    /**
     * 
     * @type {string}
     * @memberof StoreStoreItem
     */
    state?: string;
    /**
     * 
     * @type {StoreOnlineStoreSupportedCurrenciesType}
     * @memberof StoreStoreItem
     */
    supportedCurrencies?: StoreOnlineStoreSupportedCurrenciesType;
    /**
     * 
     * @type {string}
     * @memberof StoreStoreItem
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof StoreStoreItem
     */
    storeType?: string;
    /**
     * 
     * @type {string}
     * @memberof StoreStoreItem
     */
    identifier?: string;
    /**
     * 
     * @type {StoreOnlineStoreSupportedLanguagesType}
     * @memberof StoreStoreItem
     */
    supportedLanguages?: StoreOnlineStoreSupportedLanguagesType;
}


