/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StoreDatabeanResponseMasterCatalog } from './store-databean-response-master-catalog';
import { StoreDatabeanResponseStoreEntityDescription } from './store-databean-response-store-entity-description';
import { StoreDatabeanSupportedLanguages } from './store-databean-supported-languages';
import { StoreOnlineStoreRelatedStoresType } from './store-online-store-related-stores-type';

/**
 * 
 * @export
 * @interface StoreDatabeanResponse
 */
export interface StoreDatabeanResponse {
    /**
     * 
     * @type {Array<StoreOnlineStoreRelatedStoresType>}
     * @memberof StoreDatabeanResponse
     */
    relatedStores: Array<StoreOnlineStoreRelatedStoresType> | null;
    /**
     * 
     * @type {string}
     * @memberof StoreDatabeanResponse
     */
    storeLevel: string | null;
    /**
     * 
     * @type {string}
     * @memberof StoreDatabeanResponse
     */
    storeType: string;
    /**
     * 
     * @type {string}
     * @memberof StoreDatabeanResponse
     */
    jspStoreDirFilePath: string;
    /**
     * 
     * @type {string}
     * @memberof StoreDatabeanResponse
     */
    filePath: string;
    /**
     * 
     * @type {string}
     * @memberof StoreDatabeanResponse
     */
    jspStoreDir: string;
    /**
     * 
     * @type {number}
     * @memberof StoreDatabeanResponse
     */
    persistentSession: number;
    /**
     * 
     * @type {string}
     * @memberof StoreDatabeanResponse
     */
    directory: string;
    /**
     * 
     * @type {string}
     * @memberof StoreDatabeanResponse
     */
    jspPath: string;
    /**
     * 
     * @type {StoreDatabeanResponseMasterCatalog}
     * @memberof StoreDatabeanResponse
     */
    masterCatalog: StoreDatabeanResponseMasterCatalog;
    /**
     * 
     * @type {StoreDatabeanResponseStoreEntityDescription}
     * @memberof StoreDatabeanResponse
     */
    storeEntityDescription: StoreDatabeanResponseStoreEntityDescription;
    /**
     * 
     * @type {Array<StoreDatabeanSupportedLanguages>}
     * @memberof StoreDatabeanResponse
     */
    supportedLanguages: Array<StoreDatabeanSupportedLanguages>;
    /**
     * 
     * @type {number}
     * @memberof StoreDatabeanResponse
     */
    status: number;
}


