/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The descriptions of the trading agreement.
 * @export
 * @interface TradingAgreementDescription
 */
export interface TradingAgreementDescription {
    /**
     * The short description of the trading agreement.
     * @type {string}
     * @memberof TradingAgreementDescription
     */
    shortDescription?: string;
    /**
     * The long description of the trading agreement.
     * @type {string}
     * @memberof TradingAgreementDescription
     */
    longDescription?: string;
    /**
     * The locale of the descriptions. For example, en_US.
     * @type {string}
     * @memberof TradingAgreementDescription
     */
    locale?: string;
}


