/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WidgetDefinitionDescriptionUserDataField } from './widget-definition-description-user-data-field';

/**
 * 
 * @export
 * @interface WidgetDefinitionDescription
 */
export interface WidgetDefinitionDescription {
    /**
     * 
     * @type {Array<WidgetDefinitionDescriptionUserDataField>}
     * @memberof WidgetDefinitionDescription
     */
    userDataField?: Array<WidgetDefinitionDescriptionUserDataField>;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionDescription
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionDescription
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetDefinitionDescription
     */
    langId?: string;
}


