/* tslint:disable */
/* eslint-disable */
/**
 * HCL Commerce Services - Account and Contract
 * These services provide APIs to manage accounts and contracts.  a contract is an agreement that represents the terms and conditions that apply to a transaction. An account is a relationship between the merchant and the financial institution that processes transactions for that merchant.
 *
 * The version of the OpenAPI document: 9.1.6
 * 
 * (C) Copyright HCL Technologies Limited 2021
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WishlistWishlistItem } from './wishlist-wishlist-item';

/**
 * 
 * @export
 * @interface WishlistWishlist
 */
export interface WishlistWishlist {
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlist
     */
    recordSetCount?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlist
     */
    recordSetComplete?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlist
     */
    recordSetStartNumber?: string;
    /**
     * 
     * @type {Array<WishlistWishlistItem>}
     * @memberof WishlistWishlist
     */
    GiftList?: Array<WishlistWishlistItem>;
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlist
     */
    resourceName?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlist
     */
    resourceId?: string;
    /**
     * 
     * @type {string}
     * @memberof WishlistWishlist
     */
    recordSetTotal?: string;
}


